# C:\Users\PC\SwarmMultiAgent\schemas\reports.py

from pydantic import BaseModel, Field
from typing import List, Optional

# --- 1. Quality Assurance Report Schema ---

class TestResult(BaseModel):
    """Schema for individual test outcomes."""
    test_id: str = Field(..., description="Unique identifier for the test case.")
    status: str = Field(..., description="Result of the test: 'pass', 'fail', or 'skip'.")
    details: Optional[str] = Field(None, description="Detailed failure message or notes if applicable.")

class QualityAssuranceReport(BaseModel):
    """
    Schema for the final QA report generated by the TestingQAAgent.
    """
    tests_run: int = Field(..., description="Total number of tests executed.")
    tests_passed: int = Field(..., description="Total number of tests that passed successfully.")
    tests_failed: int = Field(..., description="Total number of tests that failed.")
    test_results: List[TestResult] = Field(..., description="Detailed outcomes for each test run.")
    overall_status: str = Field(..., description="Overall compliance status: 'Pass' or 'Fail'.")
    summary: str = Field(..., description="A summary of the QA findings and recommendation.")


# --- 2. Security Compliance Report Schema (The Missing Definition) ---

class SecurityFinding(BaseModel):
    """Schema for individual security issues found during audit."""
    risk_level: str = Field(..., description="Risk level: 'Critical', 'High', 'Medium', 'Low', 'Informational'.")
    vulnerability: str = Field(..., description="Description of the security vulnerability found (e.g., 'SQL Injection risk').")
    location: str = Field(..., description="File or component where the issue was found.")
    recommendation: str = Field(..., description="Action required to fix the vulnerability.")

class SecurityComplianceReport(BaseModel):
    """
    Schema for the security audit report generated by the SecurityOfficerAgent.
    """
    audit_target: str = Field(..., description="The component or artifact that was audited (e.g., 'UserAuthService.py').")
    compliance_standard: str = Field("OWASP Top 10 / SACM Policy", description="The policy or standard used for the audit.")
    findings: List[SecurityFinding] = Field(..., description="A list of all security findings.")
    critical_risk_count: int = Field(..., description="Count of critical security findings.")
    overall_compliance: str = Field(..., description="Final compliance status: 'Compliant' or 'Non-Compliant'.")
    ciso_notes: str = Field(..., description="Security Officer's final assessment and sign-off notes.")